package LoanCalculator;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
/*
Author : MUHAMAD ASHRAFF BIN OTHMAN
         52213120560
*/
public class LoanCalculatorUI extends javax.swing.JFrame {

    public LoanCalculatorUI() {
        initComponents();
        labelMsg.setText("");
        
        
        //GROUP RADIO BUTTON
        ButtonGroup btg = new ButtonGroup();
        btg.add(jcbmDefault);
        btg.add(jcbmMaroon);
        btg.add(jcbmPurple);
        btg.add(jcbmGreen);
        
    }//DEFAULT CONSTRUCTOR
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textfieldinterestRate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textfieldYears = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textfieldLoanamount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calculateBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblmonthPay = new javax.swing.JLabel();
        lbltotalPay = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        lbltotInterest = new javax.swing.JLabel();
        labelMsg = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCalculate = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmClear = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jrbShowTotalInterest = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jcbmDefault = new javax.swing.JCheckBoxMenuItem();
        jcbmMaroon = new javax.swing.JCheckBoxMenuItem();
        jcbmPurple = new javax.swing.JCheckBoxMenuItem();
        jcbmGreen = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Calculator");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(481, 458));
        jPanel1.setMinimumSize(new java.awt.Dimension(481, 458));

        labelTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitle.setText("Loan Calculator");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Annual Interest Rate :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 26, -1, -1));

        textfieldinterestRate.setText("4.5");
        jPanel2.add(textfieldinterestRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 23, 258, -1));

        jLabel2.setText("Number of Years :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 64, -1, -1));

        textfieldYears.setText("4");
        jPanel2.add(textfieldYears, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 61, 258, -1));

        jLabel3.setText("Loan Amount :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 102, -1, -1));

        textfieldLoanamount.setText("5000");
        jPanel2.add(textfieldLoanamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 99, 258, -1));

        jLabel4.setText("Monthly Payment :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 158, -1, -1));

        jLabel5.setText("Total Payment :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        calculateBtn.setText("Calculate");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(calculateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 270, 122, -1));

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 270, 95, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 137, 407, 10));

        lblmonthPay.setText("RM 0");
        jPanel2.add(lblmonthPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 158, 245, -1));

        lbltotalPay.setText("RM 0");
        jPanel2.add(lbltotalPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 190, 245, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 247, 407, 17));

        jLabel8.setText("Total Interest :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 222, -1, -1));

        lbltotInterest.setText("RM 0");
        jPanel2.add(lbltotInterest, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 222, 245, -1));

        labelMsg.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        labelMsg.setForeground(new java.awt.Color(204, 0, 102));
        labelMsg.setText("labelMsg");
        jPanel2.add(labelMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 273, 149, -1));

        exitBtn.setBackground(new java.awt.Color(255, 153, 153));
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitBtn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelTitle))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTitle)
                        .addGap(32, 32, 32)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitBtn)
                .addContainerGap())
        );

        jmCalculate.setText("Loan Operation");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Calculate");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmCalculate.add(jMenuItem3);

        jmClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmClear.setText("Clear");
        jmClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClearActionPerformed(evt);
            }
        });
        jmCalculate.add(jmClear);
        jmCalculate.add(jSeparator3);

        jmExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmExit.setText("Exit");
        jmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmExitActionPerformed(evt);
            }
        });
        jmCalculate.add(jmExit);

        jMenuBar1.add(jmCalculate);

        jMenu1.setText("View");

        jrbShowTotalInterest.setSelected(true);
        jrbShowTotalInterest.setText("Show Total Interest");
        jrbShowTotalInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbShowTotalInterestActionPerformed(evt);
            }
        });
        jMenu1.add(jrbShowTotalInterest);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Theme");

        jcbmDefault.setSelected(true);
        jcbmDefault.setText("Default");
        jcbmDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbmDefaultActionPerformed(evt);
            }
        });
        jMenu3.add(jcbmDefault);

        jcbmMaroon.setSelected(true);
        jcbmMaroon.setText("Maroon");
        jcbmMaroon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbmMaroonActionPerformed(evt);
            }
        });
        jMenu3.add(jcbmMaroon);

        jcbmPurple.setSelected(true);
        jcbmPurple.setText("Purple");
        jcbmPurple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbmPurpleActionPerformed(evt);
            }
        });
        jMenu3.add(jcbmPurple);

        jcbmGreen.setSelected(true);
        jcbmGreen.setText("Green");
        jcbmGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbmGreenActionPerformed(evt);
            }
        });
        jMenu3.add(jcbmGreen);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Help");

        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        //EXIT BUTTON ACTION
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed
    
    
    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
       Calculate();
    }//GEN-LAST:event_calculateBtnActionPerformed
    
    private void Calculate(){
                //USING TRY CATCH
        try{
            //USING IF STRUCTURE
            if (textfieldinterestRate.getText().isEmpty() || textfieldLoanamount.getText().isEmpty() || textfieldYears.getText().isEmpty() )
                {
                    throw new Exception();
                }//END IF
            
            float interestRate = Float.parseFloat(textfieldinterestRate.getText());
            int years = Integer.parseInt(textfieldYears.getText());
            float loanAmount = Float.parseFloat(textfieldLoanamount.getText());
            
            //CREATE NEW OBJECT LOAN
            Loan myLoan = new Loan(interestRate, years, loanAmount);
        
            //RESULT
            double monthlyPayment = myLoan.monthlyPayment();
            double totalPayment = myLoan.totalPayment();
            double totalInterest = myLoan.totalInterest();
        
            //FETCH RESULT TO JLABEL
            lblmonthPay.setText(String.format("RM %,.2f", monthlyPayment));
            lbltotalPay.setText(String.format("RM %,.2f", totalPayment));    
            lbltotInterest.setText(String.format("RM %,.2f", totalInterest));
            
            //USING IF TO DETERMINE IF TOTAL LOAN IS MORE THAN RM 100,000
            if (totalPayment>100000){
            labelMsg.setText("Amount Exceeded !");
            new errorMsg("Loan amount has been exceeded more than RM100,000 !", "WARNING ! : Loan Amount Exceeded").getMsgbox();
            }//END IF
 
        }//END TRY
        catch(NumberFormatException e){
            new errorMsg("Value must be a number !", "ERROR : Number Format Exception").getMsgbox();
        }//END CATCH NFE
        catch (Exception e){
            new errorMsg("Text field cannot be nulled !", "ERROR : Null Value").getMsgbox();
        }//END CATCH EXCP
    }//END METHOD CALCULATE
    
    private void clearCalculation(){
        //CLEAR JTEXTFIELD
        textfieldinterestRate.setText("");
        textfieldYears.setText("");
        textfieldLoanamount.setText("");
        lblmonthPay.setText("RM 0");
        lbltotalPay.setText("RM 0");
        lbltotInterest.setText("RM 0");
        labelMsg.setText("");
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearCalculation();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmExitActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Calculate();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jmClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClearActionPerformed
         clearCalculation();
    }//GEN-LAST:event_jmClearActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        frmAbout about = new frmAbout();
        about.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jrbShowTotalInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbShowTotalInterestActionPerformed
        if (jrbShowTotalInterest.isSelected()==true){
            jLabel8.setVisible(true);
            lbltotInterest.setVisible(true);
        }
        else if (jrbShowTotalInterest.isSelected()==false){
            jLabel8.setVisible(false);
            lbltotInterest.setVisible(false);
        }
        
    }//GEN-LAST:event_jrbShowTotalInterestActionPerformed

    private void jcbmDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbmDefaultActionPerformed
        jPanel1.setBackground(new Color(255,255,204));
        labelTitle.setForeground(Color.black);
    }//GEN-LAST:event_jcbmDefaultActionPerformed

    private void jcbmMaroonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbmMaroonActionPerformed
        jPanel1.setBackground(new Color(151,64,99));
        labelTitle.setForeground(Color.white);
    }//GEN-LAST:event_jcbmMaroonActionPerformed

    private void jcbmPurpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbmPurpleActionPerformed
        jPanel1.setBackground(new Color(106,29,128));
        labelTitle.setForeground(Color.white);
    }//GEN-LAST:event_jcbmPurpleActionPerformed

    private void jcbmGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbmGreenActionPerformed
        jPanel1.setBackground(new Color(149,226,127));
        labelTitle.setForeground(Color.black);
    }//GEN-LAST:event_jcbmGreenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanCalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanCalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanCalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanCalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanCalculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JCheckBoxMenuItem jcbmDefault;
    private javax.swing.JCheckBoxMenuItem jcbmGreen;
    private javax.swing.JCheckBoxMenuItem jcbmMaroon;
    private javax.swing.JCheckBoxMenuItem jcbmPurple;
    private javax.swing.JMenu jmCalculate;
    private javax.swing.JMenuItem jmClear;
    private javax.swing.JMenuItem jmExit;
    private javax.swing.JRadioButtonMenuItem jrbShowTotalInterest;
    private javax.swing.JLabel labelMsg;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel lblmonthPay;
    private javax.swing.JLabel lbltotInterest;
    private javax.swing.JLabel lbltotalPay;
    private javax.swing.JTextField textfieldLoanamount;
    private javax.swing.JTextField textfieldYears;
    private javax.swing.JTextField textfieldinterestRate;
    // End of variables declaration//GEN-END:variables

    
}
